[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
otc_swap = "BkCS4J3v38Pfr5U37qXqdGfJr7YDHKrKutdctJg1caxv"

[registry]
url = "https://api.apr.dev"

[cluster]
localnet = "http://localhost:8900"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

